# Site settings
title: Francisco Velazquez
email: kikin81@gmail.com
description: Francisco Velazquez personal blog site about software development life in the California Bay Area.
twitter_username: kikin81
github_username: kikin81
minimal_mistakes_skin: dark
search: true
words_per_minute: 200
site.locale: en-US

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles

# Analytics
analytics:
  provider: google
  google:
    tracking_id: UA-41149470-1
    anonymize_ip: false
# google seo
google_site_verification: cVblbcvaADqAyPz4PghXPiAodyz33PG9GITL7OEzJss

# twitter
twitter:
  username: "kikin81"

social:
  type:  Person
  name:  Francisco Velazquez
  links:
    - "https://twitter.com/kikin81"
    - "https://www.facebook.com/fsvelazquez"
    - "https://instagram.com/kikin81"
    - "https://www.linkedin.com/in/fsvelazquez"

comments:
  provider: disqus
  disqus:
    shortname: franciscovelazquez-com

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Francisco Velazquez"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "Android Software Enginner at Turo."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://franciscovelazquez.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kikin81"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kikin81"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kikin81"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kikin81"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kikin81"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kikin81"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
